import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./domain/home/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gradient-to-r from-background to-background-gradient h-screen" >
        <Header/>{children}
      </body>
    </html>
  );
}
